#ifndef __THE_LICK_H__
#define __THE_LICK_H__

#include "notes.h"

#define THE_LICK_DIMENSION  7
#define THE_LICK_NOTES {NOTE_D4, NOTE_E4, NOTE_F4, NOTE_G4, NOTE_E4, NOTE_C4, NOTE_D4}
#define THE_LICK_DURATIONS {EIGHT_NOTE,EIGHT_NOTE,EIGHT_NOTE,EIGHT_NOTE,QUARTER_NOTE,EIGHT_NOTE,WHOLE_NOTE}
#define THE_LICK_INFORMATIONS "the lick"
#endif
