#ifndef __THE_LICK_H__
#define __THE_LICK_H__

#include "notes.h"

#define THE_LICK_DIMENSION  8
#define THE_LICK_NOTES {NOTE_D4, NOTE_E4, NOTE_F4, NOTE_G4, NOTE_E4, NOTE_C4, NOTE_D4,REST}
#define THE_LICK_DURATIONS {SIXTEENTH_NOTE,SIXTEENTH_NOTE,SIXTEENTH_NOTE,SIXTEENTH_NOTE,EIGHT_NOTE,SIXTEENTH_NOTE,QUARTER_NOTE,HALF_NOTE}
#define THE_LICK_INFORMATIONS "the lick"

#endif
